#!/bin/bash

if [ -z "$(ls -A ~/Music/Playlists)" ]; then
    printf "There is no playlist available in \"~/Music/Playlists\".\n"
    read -p "Create a new playlist? (y/n) " PROMPT_FOR_PLAYLIST
    if [ $PROMPT_FOR_PLAYLIST == "y" ] || [ $PROMPT_FOR_PLAYLIST == "Y" ] || \
        [ $PROMPT_FOR_PLAYLIST == "yes" ] || [ $PROMPT_FOR_PLAYLIST == "Yes" ]; then
        printf "Enter playlist name\n"
        read -p "~> " PLAYLIST_NAME
        mkdir "$HOME/Music/Playlists/$PLAYLIST_NAME"
        printf "!! New playlist has been created.\n"
    else
        printf "!! No playlist has been created; Exiting program.\n"
    fi
    exit
fi

let i=0

PLAYLISTS=()
SONGS=()

# Options for actions to do with selected playlist
PLAYLIST_OPTIONS=(
    "1" "Add a song to playlist"
    "2" "Remove song from playlist"
    "3" "View songs in playlist"
    "4" "Delete playlist"
)

# Enumerate playlists and add to array
while read -r line; do
    let i=$i+1
    PLAYLISTS+=($i "$line")
done < <( find $HOME/Music/Playlists -mindepth 1 -maxdepth 1 -type d )

# Ask to choose a playlist
while true; do
    PLAYLIST=$(whiptail --clear --title "plipple: Choose a playlist" --menu "Choose a playlist:" 24 80 17 "${PLAYLISTS[@]}" 3>&2 2>&1 1>&3) # show dialog and store output

    if [ $? -eq 1 ]; then
        exit 1
    fi

    PLAYLIST=$(find "$HOME/Music/Playlists/" -mindepth 1 -maxdepth 1 -type d | sed -n "$PLAYLIST p")

    # Testing: ask for action to do with playlist
    ACTION=$(whiptail --clear --title "plipple: Playlist options" --menu "Playlist options" 24 80 17 "${PLAYLIST_OPTIONS[@]}" 3>&2 2>&1 1>&3)

    if [ $? -eq 1 ]; then
        continue
    fi

    if [ $ACTION -eq 1 ]; then
        SONGS=()
        let i=0
        while read -r line; do
            let i=$i+1
            SONGS+=($i "$line")
        done < <( find "$HOME/Music/" -mindepth 1 -type f )
        CHOSEN_SONG=$(whiptail --clear --title "plipple: Add a song" --menu "Add a song" 24 80 17 "${SONGS[@]}" 3>&2 2>&1 1>&3)

        if [ $? -eq 1 ]; then
            continue
        fi

        CHOSEN_SONG=$(find "$HOME/Music/" -mindepth 1 -type f | sed -n "$CHOSEN_SONG p")
        ln -s "$CHOSEN_SONG" "$PLAYLIST"
    elif [ $ACTION -eq 2 ]; then
        # Check whether songs are available in the chosen playlist or not
        if [ -z "$(ls "$PLAYLIST")" ]; then
            printf "There are no songs available in the chosen playlist.\n"
            exit 1
        fi

        SONGS=()
        let i=0
        while read -r line; do
            let i=$i+1
            SONGS+=($i "$line")
        done < <( find "$PLAYLIST" -mindepth 1 )
        CHOSEN_SONG=$(whiptail --clear --title "plipple: Remove a song" --menu "Remove a song" 24 80 17 "${SONGS[@]}" 3>&2 2>&1 1>&3)

        if [ $? -eq 1 ]; then
            continue
        fi

        CHOSEN_SONG=$(find "$PLAYLIST" -mindepth 1 | sed -n "$CHOSEN_SONG p")
        rm "$CHOSEN_SONG"
    elif [ $ACTION -eq 3 ]; then
        # Check whether songs are available in the chosen playlist or not
        if [ -z "$(ls "$PLAYLIST")" ]; then
            printf "There are no songs available in the chosen playlist.\n"
            exit 1
        fi

        SONGS=()
        let i=0
        while read -r line; do
            let i=$i+1
            SONGS+=($i "$line")
        done < <( find "$PLAYLIST" -mindepth 1 )
        whiptail --clear --title "plipple: Available songs" --menu "Available songs in the playlist" 24 80 17 "${SONGS[@]}" 3>&2 2>&1 1>&3

        if [ $? -eq 1 ]; then
            continue
        fi

    fi
done
